SHOW TABLES

DROP TABLE IF EXISTS `basic_goods_info`;
CREATE TABLE `basic_goods_info` (
  `BGI_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '商品编号',
  `BGI_NAME` VARCHAR(20) DEFAULT NULL COMMENT '商品名称',
  `BGI_PRICE` DECIMAL(8,2) DEFAULT NULL COMMENT '单价',
  `BGI_UNIT` VARCHAR(10) DEFAULT NULL COMMENT '单位',
  PRIMARY KEY (`BGI_ID`)
) ENGINE=INNODB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='商品基本信息';