server:
  port: 9021

simple:
  host: 0.0.0.0
  port: 35672
  username: guest
  password: guest
  virtual-host: simple
  listener:
    simple:
      concurrency: 1
      max-concurrency: 3
      prefetch: 6

my:
  host: 0.0.0.0
  port: 35672
  username: guest
  password: guest
  virtual-host: my
  listener:
    simple:
      concurrency: 1
      max-concurrency: 3
      prefetch: 6